checks:
  complex-logic:
    config:
      threshold: 50
  file-lines:
    config:
      threshold: 500
  method-complexity:
    config:
      threshold: 50
  method-lines:
    config:
      threshold: 50
  similar-code:
    config:
      threshold: 120
  identical-code:
    config:
      threshold: 120

exclude_patterns:
  - "**/test/"
  - "**/androidTest/"
  - "**test"
